### ISSUE TITLE
bug: dns requests are not cached

### ISSUE THREAD

**Issue by SeDemal** [homarr-labs/homarr#1141]
### Provide environment information

any

### Describe the bug

Some queries are not cached but should. This results in an insane amount of queries (This is a 7h span).
This is because the media information for each element needs to be queried separately, resulting in 20 calls every 5 seconds.
![image](https://github.com/user-attachments/assets/470abf5a-0313-48b9-a0b5-e3b26a6cbbb7)

### To reproduce

Mostly visible using the media request widgets.
Let the page opened for a while then go check your queries in pihole.

**Comment by manuel-rw** [comment]
I think the requests are behaving as designed - we don't know whether the remote data has changed or not - therefore we must fetch all the time.
However, 128K DNS requests do seem extreme - I wonder whether we don't properly cache DNS resolve requests.
@SeDemal can you confirm, that the problem is the **amount of DNS requests** and not the **amount & frequency of HTTP requests**? As far as I saw, we cannot reduce the amount of HTTP requests (except the frequency) because the data we need is distributed over multiple API endpoints.

**Comment by bonovski** [comment]
I had to stop the container, because tasks.cjs burns CPU cycles and spams pihole constantly.

**Comment by manuel-rw** [comment]
I'm analyzing this now. I will dump some requests using Wireshark first...

**Comment by manuel-rw** [comment]
Here are my findings so far:
- Homarr uses ``undici`` to fetch data from integrations, which does not have any DNS caching by itself. It always lookups all hostnames with a DNS request, which is visible in Wireshark: <br/> ![Image](https://github.com/user-attachments/assets/45569876-e4b0-4df2-9e2c-73c97db7dea7)
These packets are being sent every time Homarr is fetching data from any integration or any website (e.g. GitHub or jsdelivr).
- The above is slightly odd, because [Docker will inherit the DNS settings from your host, unless you are using a custom network](https://docs.docker.com/engine/network/#dns-services). The upstream DNS server should handle DNS caching, not your application (e.g. Homarr).
- After inspecting the DNS requests with Wireshark, I noticed that PiHole is always returning a TTL of ``0`` when replying to the DNS resolve requests of Homarr: <br/>
![Image](https://github.com/user-attachments/assets/52e6b97c-eccf-4ce7-96cf-9b8963de0162)
A TTL of ``0`` means that it **expires immediately** and will (and should!) not be cached. This is normally something that your DNS will control and should not be overridden in your client, unless you know what you're doing
- [PiHole is returning a TTL of ``0`` by default for all DNS queries](https://discourse.pi-hole.net/t/change-the-ttl/6903/13) because according to their developers, it should not be cached (for too long) to reflect changes in the blacklist / whitelist quickly on clients in the network.

I did experiment with ``cacheable-lookup`` like I mentioned, but this didn't work because the TTL of PiHole is reused in my network - rendering all responses as **expired** immediately. We could possibly override this in Homarr but this is rather dangerous and could lead to very flaky behavior, especially with orchestrators and Kubernetes.

The above findings lead me to the following conclusion at this moment:
- The low TTL is a PiHole specific issue and should be configured in PiHole itself. This is described here: https://discourse.pi-hole.net/t/change-the-ttl/6903/2 . You should choose any value above 6 seconds to reduce the load on PiHole, but you'll likely need values above 60 seconds for any big differences in load to show (since Homarr fetches some requests only every 60 seconds, you'll need a TTL slightly above that, to cache at least every second request).
- Many public DNS servers [will have fixed TTLs of at least ``300`` (5 minutes) seconds](https://discourse.pi-hole.net/t/change-the-ttl/6903/2), meaning ``4``/``5`` requests will be cached for a request running every minute. 
- Both @SeDemal and myself use PiHole, which leads me to believe that this problem is PiHole (or possibly also AdGuard Home) specific. Can all people, experiencing the same problem in  this thread, confirm that they are running one of those options too? If not, please capture detailed documentation of your DNS server, Docker networking configuration and trace using WireShark (please don't upload dumps here!)

I found this really helpful post about TTL and why low TTL can be a bad idea: https://blog.apnic.net/2019/11/12/stop-using-ridiculously-low-dns-ttls/ . I highly recommend you to give it a reason and possibly re-consider your TTL setting.

Oh, and check whether your PiHole is actually caching them. If not, that could be bad, since you're "spamming" your ISP (or your upstream DNS server, like Cloudflare) with tons of requests:

![Image](https://github.com/user-attachments/assets/8d0a7321-b937-4a0b-a1a3-ebd893c488ec)

In my case, the ``(cached)`` means that it was cached within PiHole and not sent out. I have 

Can you please confirm that my theory here is correct?

**Comment by manuel-rw** [comment]
Since there is no further activity on this issue, I will close it as not fixed.
Please comment on this again if the problem has not been solved by the above described solution.

**Comment by hundehausen** [comment]
Hey @manuel-rw thank you so much for you research. 
This issue is not fixed for me, even after changing the dnsmasq config with `local-ttl=300`.
As Homarr is the only self-hosted service in my homelab, that has this issue, I think it would be best to fix this issue in Homarr. Is it possible to use anything else than `undici`  for requests?

**Comment by manuel-rw** [comment]
Hi @hundehausen , thanks for the comment.

- Can you capture using Wireshark to inspect what the TTL is? Maybe you misconfigured it or PiHole doesn't properly respect it.
- No, Homarr isn't the only application that will have this issue. But we currently have quite a bit too aggressive intervals for our queries, making too frequent requests. If you run a script, doing multiple requests per second on any device that respects TTL, you'll get the same issue as far as I can tell
- @Meierschlumpf can you answer this one? As far as I understood it is state of the art and there isn't much we could do, except migrating to axios. Axios will likely respect the TTL too (which is according to spec) and have the same behaviour.

**Comment by Meierschlumpf** [comment]
As far as I understood your research it was behaving as expected once you switched your ttl from the dns-server. So switching to axios would not change anything.

**Comment by mirko8054** [comment]
Hello, re opening the issue topic because i am having a similar scenario:

My setup is Proxmox>Deb12 OMV VM>docker managed with portainer>homarr.
The same docker manages all my applications and for each app i have a sub local domain, registered with cloudflare that points to my local network. Everything worked perfectly for over a year by now, until suddenly my network slows down to almost stop on certain things, like loading web pages, discord images and so on. Ran CMD, ping google.it = no response from DNS but i was able to ping 1.1.1.1. Took a look on my router, Mikrotik HAP Ax2 and on the logs of my network i see a massive spam for DNS requests coming up from the docker VM. Scouted portainer, NPM is the only app to read traffic in port 53 but everything clean, then i see Homarr logs and with a little surprise, logs are flooded with DNS requests for all my subdomain apps: https://pastebin.com/hmn0i9cN. As suggested from Manicraft i analyzed the traffic with wireshark and confirms what i suspected, a lot of DNS requests for the subdomains, with a TTL of 64.
I do not have any DNS client/server, i just use basic 1.1.1.1. No custom cache or anything.

**Comment by ThowZzy** [comment]
I also noticed this issue, where homarr doesn't cache the responses and spams the dns server. My dns server is Adguard Home. In the meantime, i configured my integrations URL with the docker internal names so that it resolves internally and not using the dns server.

![Image](https://github.com/user-attachments/assets/753c7b50-4e2f-40ff-8006-6d3ad66be2dd)

This fixes it for me but not ideal, also, the links from the integrations in the dashboard don't work with this setup.

**Comment by manuel-rw** [comment]
> I also noticed this issue, where homarr doesn't cache the responses and spams the dns server. My dns server is Adguard Home. In the meantime, i configured my integrations URL with the docker internal names so that it resolves internally and not using the dns server.
> 
> ![Image](https://github.com/user-attachments/assets/753c7b50-4e2f-40ff-8006-6d3ad66be2dd)
> 
> This fixes it for me but not ideal, also, the links from the integrations in the dashboard don't work with this setup.

Can you also confirm that you have a TTL > ``30``?
Otherwise, you explicitly tell Homarr to never cache the DNS response and force it to re-resolve on every request.

**Comment by cmuck** [comment]
Same issue using PiHole, tried out
* TTL of 300 and
* to disable the status checks

but unfortunately didn't help

@manuel-rw Thanks a lot for Homarr, it's a great dashboard and I really appreciate your time and effort you invest in the project. I've already tried out a lot of other dashboards but Homarr is awesome.

>To elaborate why Homarr is sending more requests than in previous versions (e.g. 0.15.10), we have background jobs that now run 24/7, even if no user is using Homarr at the moment. In contrast, the previous version only requested when there was someone using it.

Could you please elaborate why the backgrounds jobs now run 24/7 compared to v0.15.10 even if no user is using Homarr pls?

Meaning is that required from functional perspective or which technical reason/benefit requires to request the services all the time if no one is actually using the dashboard?

Don't get me wrong, just want to understand the reason behind this change since Homarr is in my eyes a dashboard solution and my services are already observed 24/7 from my monitoring+alerting solution.

Would it be fine for you to
* request the services only when someone is using Homarr or
* disable when status checks for a service are disabled or
* disable by a new feature-flag or
* make the request interval configurable by env var or
* ...

**Comment by Vaskyy** [comment]
i have 4 integrations setup: jellyfin, proxmox, pihole and home assistant.
home assistant is the only one that doesnt ask for infos so often.
maybe because i dont have a anything on the board running that is requiring too much infos?

**Comment by cmuck** [comment]
Removing the widgets for

* DNS hole - PiHole
* System health monitor - Dash

helped to reduce the amount of DNS queries

![Image](https://github.com/user-attachments/assets/d183e7ff-fe02-4458-8d87-14becf20dbe7)

**Comment by manuel-rw** [comment]
~Since they merged their fix now, do we want to try it too, @Meierschlumpf ?~

**Comment by Meierschlumpf** [comment]
The have not merged it, they had merged the old one which resulted in more problems. The relevant change is 1294 and not the 728

**Comment by gauthier-th** [comment]
Hey guys, Jellyseerr maintainer here. Do you think we should publish our DNS caching system as a package?

We ended up rewriting our own DNS caching system from scratch because none of what we found was working as we wanted, so maybe it could be helpful to others and avoid having all our own custom caching system 😅

**Comment by manuel-rw** [comment]
Thanks for reaching out. How does it differ to https://www.npmjs.com/package/cacheable-lookup ?
I haven't looked at your commits yet.
We'd be happy to give you some credit in Homarr if we reuse it :)
Does it respect TTL or ignore and defines it's own?

**Comment by gauthier-th** [comment]
The main reasons:
- `cacheable-lookup` seems no longer to be maintained
- issues with IPv4 failing to resolve in some case where IPv6 wasn't working properly (https://github.com/szmarczak/cacheable-lookup/issues/52, https://github.com/szmarczak/cacheable-lookup/issues/68)
- in the end, we encountered so much errors with users not being able to resolve their hostname after we added `cacheable-lookup` that we had to remove it
- we wanted some stats about what is cached

For the TTL, it's mostly respecting it: it's using the TTL from the DNS entry, but we set a maximum of 5min

**Comment by Meierschlumpf** [comment]
> Hey guys, Jellyseerr maintainer here. Do you think we should publish our DNS caching system as a package?
> 
> We ended up rewriting our own DNS caching system from scratch because none of what we found was working as we wanted, so maybe it could be helpful to others and avoid having all our own custom caching system 😅

That would be awesome, then we could also benefit of bug fixes on both sides, if any issues are found / add new functionalities.

**Comment by manuel-rw** [comment]
> The main reasons:
> 
>     * `cacheable-lookup` seems no longer to be maintained
> 
>     * issues with IPv4 failing to resolve in some case where IPv6 wasn't working properly ([Querying for family=6 when family=4 is explicitly requested? szmarczak/cacheable-lookup#52](https://github.com/szmarczak/cacheable-lookup/issues/52), [Cacheable lookup responds with ESERVFAIL while native dns.resolve works szmarczak/cacheable-lookup#68](https://github.com/szmarczak/cacheable-lookup/issues/68))
> 
>     * in the end, we encountered so much errors with users not being able to resolve their hostname after we added `cacheable-lookup` that we had to remove it
> 
>     * we wanted some stats about what is cached
> 
> 
> For the TTL, it's mostly respecting it: it's using the TTL from the DNS entry, but we set a maximum of 5min

Thanks for the writeup, I agree on the maintain status - it's a huge risk due to outdated dependencies.
Perhaps it even makes sense to ignore very low TTLs, such as <10: https://blog.apnic.net/2019/11/12/stop-using-ridiculously-low-dns-ttls/

We'd love to implement this in Homarr. Where are you planning to publish? We can also talk via Discord if this helps speed up the process :)

**Comment by gauthier-th** [comment]
> Perhaps it even makes sense to ignore very low TTLs, such as <10

We could make that an option. But for Jellyseerr I don't really think it's necessary: we only use a few external services, so updating the DNS entry once every 5min is ok IMO.

> Where are you planning to publish?

In the [Jellyseerr](https://github.com/jellyseerr) org? It can still move later if needed.

> We can also talk via Discord if this helps speed up the process :)

Just joined your Discord!

**Comment by Meierschlumpf** [comment]
Quick update on the state of this issue, we'll have to reorganize some stuff how we build the project and it requires a bit more time investment than we initially thought. I'll try to get started with those changes next weekend

**Comment by Meierschlumpf** [comment]
I've published the image tag `dns-caching` with a fix that contains a dns-cache for the background jobs (so most of the calls should be cached now)

Can you guys try it out and let me know if it works?

**Comment by Meierschlumpf** [comment]
@cmuck, @ThowZzy, @mirko8054, @hundehausen, @Bonovski can some of you try it out?
Sorry for pinging

**Comment by manuel-rw** [comment]
Hi, was someone able to check the fix?

**Comment by mirko8054** [comment]
Hi, sorry I can't, I'm away until September. Will definitely check when I'm back.

**Comment by hundehausen** [comment]
@manuel-rw @Meierschlumpf yes! It's fixed now in `dns-caching`. No more spamming of Pi-hole, dns reuqests are cached now.
Thank you

**Comment by Meierschlumpf** [comment]
Okay nice to hear that it worked for you 😄

**Comment by arazius** [comment]
Stumbled on this while searching for a solution, tag worked perfectly for me.

**Comment by ThowZzy** [comment]
I just tried and im not 100% sure it fixed the issue I was having, I think its not spamming anymore when not in use, but after every refresh I can still see stuff like this : 

<img width="1801" height="1962" alt="Image" src="https://github.com/user-attachments/assets/0f579291-ff52-4aa6-bc30-25f140feff92" />


Edit : After more testing it seems I still get these bursts once, but it then gets cached for a while tho

**Comment by Meierschlumpf** [comment]
Okay yeah we might want to add the dns caching to the nextjs app as well then, especially within the same request. I'll have to see how we can achieve that. Currently it is only caching in the tasks app where the calls are done every few seconds / minutes

**Comment by Meierschlumpf** [comment]
@ThowZzy can you check the latest release of the image tag `dns-caching`? Now it should also cache the requests from the nextjs app. @hundehausen @arazius if you like, you can also test it again, just to be sure that it works for you all 😉

**Comment by Meierschlumpf** [comment]
Would be nice to get some confirmations, if we get them, we can release this functionality

**Comment by hundehausen** [comment]
@Meierschlumpf it works fine 👍  Thank you

**Comment by Meierschlumpf** [comment]
As some users had issues in `v1.36.0` with the addition of this feature, we've moved it to an optional environment variable to enable it manually. You can use `ENABLE_DNS_CACHING=true` to do so. See #4006

**Comment by cylian914** [comment]
Why is the application caching dns querry? Thats the job of the dns resolver not application
